package no.f12.codenavigator

object AgentHelpText {
    fun generate(): String = buildString {
        appendLine("=== code-navigator: AI Agent Guide ===")
        appendLine()
        appendLine("code-navigator is a Gradle plugin that analyzes JVM bytecode.")
        appendLine("It gives you structural insight into a codebase without reading source files.")
        appendLine("All tasks support -Pformat=json for structured, parseable output.")
        appendLine()
        appendLine("--- Recommended Workflow ---")
        appendLine()
        appendLine("1. ORIENT: Get a high-level view of the codebase")
        appendLine("   ./gradlew cnavDeps                        # package dependency map")
        appendLine("   ./gradlew cnavDeps -Pformat=json           # same, as JSON")
        appendLine("   ./gradlew cnavListClasses                  # all classes and source files")
        appendLine()
        appendLine("2. FIND: Locate relevant code")
        appendLine("   ./gradlew cnavFindClass -Ppattern=Service  # find classes by name")
        appendLine("   ./gradlew cnavFindSymbol -Ppattern=reset   # find methods/fields by name")
        appendLine()
        appendLine("3. INSPECT: Understand a class")
        appendLine("   ./gradlew cnavClass -Ppattern=ResetPasswordService")
        appendLine("   # Shows fields, methods, superclass, and implemented interfaces")
        appendLine()
        appendLine("4. TRACE: Follow the call graph")
        appendLine("   ./gradlew cnavCallers -Pmethod=resetPassword -Pmaxdepth=3 -Pprojectonly=true  # who calls this?")
        appendLine("   ./gradlew cnavCallees -Pmethod=handleRequest -Pmaxdepth=3 -Pprojectonly=false  # what does this call?")
        appendLine("   # -Pprojectonly=true hides JDK/stdlib noise")
        appendLine("   # -Pmaxdepth=5 for deeper traversal")
        appendLine()
        appendLine("5. MAP: Understand abstractions")
        appendLine("   ./gradlew cnavInterfaces -Ppattern=Repository")
        appendLine("   # Add -Pincludetest=true to see test fakes and stubs")
        appendLine()
        appendLine("--- Task Reference ---")
        appendLine()
        appendLine("  cnavListClasses           List all classes and source files")
        appendLine("  cnavFindClass             Find classes by regex       -Ppattern=<regex>")
        appendLine("  cnavFindSymbol            Find methods/fields         -Ppattern=<regex>")
        appendLine("  cnavClass                 Inspect class signature     -Ppattern=<regex>")
        appendLine("  cnavCallers               Who calls a method?         -Pmethod=<regex>")
        appendLine("  cnavCallees               What does a method call?    -Pmethod=<regex>")
        appendLine("  cnavInterfaces            Find implementations        -Ppattern=<regex>")
        appendLine("  cnavDeps                  Package dependency map      [-Ppackage=<regex>]")
        appendLine()
        appendLine("--- Global Parameters ---")
        appendLine()
        appendLine("  -Pformat=json             Machine-readable JSON output (all tasks)")
        appendLine("  -Pprojectonly=true         Hide JDK/stdlib (cnavCallers, cnavCallees, cnavDeps)")
        appendLine("  -Pmaxdepth=N              Max call tree depth (cnavCallers, cnavCallees)")
        appendLine("  -Preverse=true            Reverse deps: who depends on me? (cnavDeps)")
        appendLine("  -Pincludetest=true        Include test classes (cnavInterfaces)")
        appendLine()
        appendLine("--- Tips for Optimal Results ---")
        appendLine()
        appendLine("- Always use -Pformat=json. It is faster to parse than human-readable tables.")
        appendLine("- Use -Pprojectonly=true to cut noise. External call chains are rarely useful.")
        appendLine("- Patterns are Java regex, case-insensitive. Use .* for wildcards.")
        appendLine("- cnavDeps is the fastest way to understand module/package structure.")
        appendLine("- cnavClass is cheaper than reading a source file when you only need the API surface.")
        appendLine("- Chain tasks: find a class, inspect it, then trace its callers — each step narrows context.")
        appendLine("- Results are cached on disk. Repeated runs are fast (~400ms Gradle overhead).")
        appendLine("- Run ./gradlew cnavHelp for full parameter documentation.")
    }
}
