package no.f12.codenavigator

object HelpText {
    fun generate(): String = buildString {
        appendLine("=== code-navigator plugin ===")
        appendLine()
        appendLine("All tasks support -Pformat=json for machine-readable JSON output.")
        appendLine()
        appendLine("Available tasks:")
        appendLine()
        appendLine("  cnavHelp")
        appendLine("    Shows this help text.")
        appendLine("    Usage: ./gradlew cnavHelp")
        appendLine()
        appendLine("  cnavListClasses")
        appendLine("    Lists all classes in the project and their source files.")
        appendLine("    Scans compiled bytecode from the main source set.")
        appendLine("    Usage: ./gradlew cnavListClasses")
        appendLine()
        appendLine("  cnavFindClass")
        appendLine("    Searches for classes matching a regex pattern.")
        appendLine("    Matches against both class name and source file path (case-insensitive).")
        appendLine("    Parameters:")
        appendLine("      -Ppattern=<regex>  (required) Regex to match against class names and source paths")
        appendLine("    Usage: ./gradlew cnavFindClass -Ppattern=Service")
        appendLine("    Usage: ./gradlew cnavFindClass -Ppattern=\".*Reset.*\"")
        appendLine("    Usage: ./gradlew cnavFindClass -Ppattern=\"domain\\..*\"")
        appendLine()
        appendLine("  cnavFindSymbol")
        appendLine("    Searches for symbols (methods, fields) matching a regex pattern.")
        appendLine("    Matches against package, class name, symbol name, and source file (case-insensitive).")
        appendLine("    Filters out constructors, synthetic methods, property accessors, and data class generated methods.")
        appendLine("    Output columns: Package | Class | Symbol | Kind | Source File")
        appendLine("    Parameters:")
        appendLine("      -Ppattern=<regex>  (required) Regex to match against symbol information")
        appendLine("    Usage: ./gradlew cnavFindSymbol -Ppattern=resetPassword")
        appendLine("    Usage: ./gradlew cnavFindSymbol -Ppattern=\".*Service.*\"")
        appendLine("    Usage: ./gradlew cnavFindSymbol -Ppattern=\"find.*\"")
        appendLine()
        appendLine("  cnavCallers")
        appendLine("    Shows who calls a given method, displayed as an indented tree.")
        appendLine("    Scans compiled bytecode to build a call graph, then walks callers transitively.")
        appendLine("    Parameters:")
        appendLine("      -Pmethod=<regex>      (required) Regex to match against Class.method names")
        appendLine("      -Pmaxdepth=<N>        (required) Maximum depth of caller tree")
        appendLine("      -Pprojectonly=true     (optional) Filter to project classes only, hiding JDK/stdlib noise")
        appendLine("    Usage: ./gradlew cnavCallers -Pmethod=resetPassword -Pmaxdepth=3")
        appendLine("    Usage: ./gradlew cnavCallers -Pmethod=\".*Service\\.find.*\" -Pmaxdepth=5")
        appendLine("    Usage: ./gradlew cnavCallers -Pmethod=\"Repo\\.save\" -Pmaxdepth=5 -Pprojectonly=true")
        appendLine()
        appendLine("  cnavCallees")
        appendLine("    Shows what a method calls, displayed as an indented tree.")
        appendLine("    Scans compiled bytecode to build a call graph, then walks callees transitively.")
        appendLine("    Parameters:")
        appendLine("      -Pmethod=<regex>      (required) Regex to match against Class.method names")
        appendLine("      -Pmaxdepth=<N>        (required) Maximum depth of callee tree")
        appendLine("      -Pprojectonly=true     (optional) Filter to project classes only, hiding JDK/stdlib noise")
        appendLine("    Usage: ./gradlew cnavCallees -Pmethod=resetPassword -Pmaxdepth=3")
        appendLine("    Usage: ./gradlew cnavCallees -Pmethod=\".*Controller\\.handle.*\" -Pmaxdepth=5")
        appendLine("    Usage: ./gradlew cnavCallees -Pmethod=\"Service\\.create\" -Pmaxdepth=5 -Pprojectonly=true")
        appendLine()
        appendLine("  cnavClass")
        appendLine("    Shows class signature: fields, methods, superclass, and implemented interfaces.")
        appendLine("    Filters out constructors, synthetic methods, property accessors, and data class boilerplate.")
        appendLine("    Parameters:")
        appendLine("      -Ppattern=<regex>  (required) Regex to match against class names")
        appendLine("    Usage: ./gradlew cnavClass -Ppattern=ResetPasswordService")
        appendLine("    Usage: ./gradlew cnavClass -Ppattern=\".*Client\"")
        appendLine("    Usage: ./gradlew cnavClass -Ppattern=\"domain\\.DomainError\"")
        appendLine()
        appendLine("  cnavInterfaces")
        appendLine("    Finds classes that implement a given interface.")
        appendLine("    Scans compiled bytecode to build an interface-to-implementors map.")
        appendLine("    Parameters:")
        appendLine("      -Ppattern=<regex>     (required) Regex to match against interface names")
        appendLine("      -Pincludetest=true    (optional) Include test source set to find test fakes/stubs")
        appendLine("    Usage: ./gradlew cnavInterfaces -Ppattern=Repository")
        appendLine("    Usage: ./gradlew cnavInterfaces -Ppattern=\".*Client\"")
        appendLine("    Usage: ./gradlew cnavInterfaces -Ppattern=\"services\\.interfaces\\..*\"")
        appendLine("    Usage: ./gradlew cnavInterfaces -Ppattern=Repository -Pincludetest=true")
        appendLine()
        appendLine("  cnavDeps")
        appendLine("    Shows package-level dependencies — which packages call into which other packages.")
        appendLine("    Aggregates the call graph by package, excluding self-dependencies.")
        appendLine("    Without -Ppackage, shows all packages. With -Ppackage, filters to matching packages.")
        appendLine("    With -Preverse=true, shows reverse dependencies (who depends on each package).")
        appendLine("    Parameters:")
        appendLine("      -Ppackage=<regex>    (optional) Regex to match against package names")
        appendLine("      -Preverse=true       (optional) Show reverse dependencies (incoming instead of outgoing)")
        appendLine("      -Pprojectonly=true   (optional) Filter to project classes only, hiding JDK/stdlib noise")
        appendLine("    Usage: ./gradlew cnavDeps")
        appendLine("    Usage: ./gradlew cnavDeps -Ppackage=services")
        appendLine("    Usage: ./gradlew cnavDeps -Ppackage=\"ktor\\.routes\"")
        appendLine("    Usage: ./gradlew cnavDeps -Preverse=true")
        appendLine("    Usage: ./gradlew cnavDeps -Ppackage=domain -Preverse=true")
        appendLine("    Usage: ./gradlew cnavDeps -Pprojectonly=true")
        appendLine()
        appendLine("  cnavAgentHelp")
        appendLine("    Shows detailed instructions for AI coding agents on how to use code-navigator effectively.")
        appendLine("    Includes recommended workflows, task selection guidance, and tips for optimal results.")
        appendLine("    Usage: ./gradlew cnavAgentHelp")
        appendLine()
        appendLine("--- Git History Analysis Tasks ---")
        appendLine()
        appendLine("These tasks analyze git history and do NOT require compilation.")
        appendLine("All share the parameter: -Pafter=YYYY-MM-DD (default: 1 year ago)")
        appendLine()
        appendLine("  cnavHotspots")
        appendLine("    Ranks files by change frequency. The most-changed files are where development")
        appendLine("    effort concentrates — priority refactoring targets if they also have structural problems.")
        appendLine("    Parameters:")
        appendLine("      -Pafter=YYYY-MM-DD     (optional) Only consider commits after this date (default: 1 year ago)")
        appendLine("      -Pmin-revs=N           (optional) Minimum revisions to include (default: 1)")
        appendLine("      -Ptop=N                (optional) Maximum results to return (default: 50)")
        appendLine("    Usage: ./gradlew cnavHotspots")
        appendLine("    Usage: ./gradlew cnavHotspots -Pafter=2024-01-01 -Pmin-revs=5 -Ptop=20")
        appendLine()
        appendLine("  cnavCoupling")
        appendLine("    Finds files that change together in the same commits — implicit dependencies invisible")
        appendLine("    in call graphs. Complements structural cnavDeps with behavioral coupling data.")
        appendLine("    Parameters:")
        appendLine("      -Pafter=YYYY-MM-DD          (optional) Only consider commits after this date (default: 1 year ago)")
        appendLine("      -Pmin-shared-revs=N         (optional) Minimum shared commits to report (default: 5)")
        appendLine("      -Pmin-coupling=N            (optional) Minimum coupling degree % (default: 30)")
        appendLine("      -Pmax-changeset-size=N      (optional) Skip commits touching more files (default: 30)")
        appendLine("    Usage: ./gradlew cnavCoupling")
        appendLine("    Usage: ./gradlew cnavCoupling -Pmin-shared-revs=10 -Pmin-coupling=50")
        appendLine()
        appendLine("  cnavAge")
        appendLine("    Measures time since last modification per file. Stable old code is good;")
        appendLine("    frequently-changing old code with structural problems is a hotspot.")
        appendLine("    Parameters:")
        appendLine("      -Pafter=YYYY-MM-DD     (optional) Only consider commits after this date (default: 1 year ago)")
        appendLine("      -Ptop=N                (optional) Maximum results to return (default: 50)")
        appendLine("    Usage: ./gradlew cnavAge")
        appendLine("    Usage: ./gradlew cnavAge -Pafter=2023-01-01 -Ptop=20")
        appendLine()
        appendLine("  cnavAuthors")
        appendLine("    Number of distinct contributors per file. More developers on a module means")
        appendLine("    larger communication challenges. High author counts correlate with defects.")
        appendLine("    Parameters:")
        appendLine("      -Pafter=YYYY-MM-DD     (optional) Only consider commits after this date (default: 1 year ago)")
        appendLine("      -Pmin-revs=N           (optional) Minimum revisions to include (default: 1)")
        appendLine("      -Ptop=N                (optional) Maximum results to return (default: 50)")
        appendLine("    Usage: ./gradlew cnavAuthors")
        appendLine("    Usage: ./gradlew cnavAuthors -Pmin-revs=3 -Ptop=20")
        appendLine()
        appendLine("  cnavChurn")
        appendLine("    Measures lines added/deleted per file. Pre-release churn is a good predictor")
        appendLine("    of post-release defects.")
        appendLine("    Parameters:")
        appendLine("      -Pafter=YYYY-MM-DD     (optional) Only consider commits after this date (default: 1 year ago)")
        appendLine("      -Ptop=N                (optional) Maximum results to return (default: 50)")
        appendLine("    Usage: ./gradlew cnavChurn")
        appendLine("    Usage: ./gradlew cnavChurn -Pafter=2024-06-01 -Ptop=30")
    }
}
