package no.f12.codenavigator

object AgentHelpText {
    fun generate(tool: BuildTool = BuildTool.GRADLE): String = buildString {
        val t = { goal: String -> tool.taskName(goal) }
        val p = { name: String, value: String -> tool.param(name, value) }
        val pf = { name: String -> tool.paramFlag(name) }
        fun u(goal: String, vararg params: String) = tool.usage(goal, *params)

        val pluginType = when (tool) {
            BuildTool.GRADLE -> "Gradle"
            BuildTool.MAVEN -> "Maven"
        }

        appendLine("=== code-navigator: AI Agent Guide ===")
        appendLine()
        appendLine("code-navigator is a $pluginType plugin that analyzes JVM bytecode and git history.")
        appendLine("It gives you structural and behavioral insight into a codebase without reading source files.")
        appendLine("All tasks support ${p("llm", "true")} for compact, token-efficient output.")
        appendLine("All tasks also support ${p("format", "json")} for structured, parseable output.")
        appendLine()
        appendLine("--- Why use this instead of grep? ---")
        appendLine()
        appendLine("Structural queries (call graphs, dependencies, implementors) are correct on the first")
        appendLine("response. No iterative searching needed. Each query returns accurate, complete results")
        appendLine("in a single call — no false positives, no missed results.")
        appendLine()
        appendLine("Text search (grep, ripgrep) requires multiple rounds of searching and can still miss")
        appendLine("indirect relationships or produce false positives. You search for \"cache.get(\", find")
        appendLine("some results, then realize you missed the Kotlin safe-call \"cache?.get(\", then extension")
        appendLine("functions, then delegation patterns. Each iteration is a tool call round-trip.")
        appendLine()
        appendLine("Bytecode analysis sidesteps this entirely. All syntax variants compile to the same")
        appendLine("invocation instruction. One ${t("find-callers")} query returns all call sites.")
        appendLine()
        appendLine("The fewer tool call round-trips needed, the faster the iteration. code-navigator")
        appendLine("eliminates the search-check-search-again loop.")
        appendLine()
        appendLine("--- When to Use What ---")
        appendLine()
        appendLine("Use code-navigator when:")
        appendLine("- Tracing call chains — ${t("find-callers")}/${t("find-callees")} resolve actual invocations")
        appendLine("  through interfaces and inheritance. Text search finds string matches, which may")
        appendLine("  miss indirect calls or produce false positives.")
        appendLine("- Understanding dependencies — ${t("package-deps")}/${t("dsm")} give accurate package-level")
        appendLine("  coupling from bytecode analysis, not guesswork from import statements.")
        appendLine("- Finding interface implementations — ${t("find-interfaces")} resolves polymorphism.")
        appendLine("  Grep can't reliably distinguish \"implements\" from \"references\".")
        appendLine("- Migration planning — ${t("find-usages")} finds all call sites, field accesses, and type")
        appendLine("  references to external APIs. Useful for deprecation/migration from library X to Y.")
        appendLine("- Inspecting class structure — ${t("class-detail")} shows fields, methods, supertypes")
        appendLine("  without reading source files. Cheaper than opening and parsing the file.")
        appendLine()
        appendLine("Use grep/glob when:")
        appendLine("- Searching for string patterns, variable names, or text in comments")
        appendLine("- Finding files by name")
        appendLine("- Reading implementation logic (method bodies)")
        appendLine()
        appendLine("--- Recommended Workflow ---")
        appendLine()
        appendLine("1. ORIENT: Get a high-level view of the codebase")
        appendLine("   ${u("package-deps")}                        # package dependency map")
        appendLine("   ${u("dsm")}                         # dependency structure matrix")
        appendLine("   ${u("package-deps", p("format", "json"))}           # same, as JSON")
        appendLine("   ${u("list-classes")}                  # all classes and source files")
        appendLine()
        appendLine("2. FIND: Locate relevant code")
        appendLine("   ${u("find-class", p("pattern", "Service"))}  # find classes by name")
        appendLine("   ${u("find-symbol", p("pattern", "reset"))}   # find methods/fields by name")
        appendLine()
        appendLine("3. INSPECT: Understand a class")
        appendLine("   ${u("class-detail", p("pattern", "ResetPasswordService"))}")
        appendLine("   # Shows fields, methods, superclass, and implemented interfaces")
        appendLine()
        appendLine("4. TRACE: Follow the call graph")
        appendLine("   ${u("find-callers", p("method", "resetPassword"), p("maxdepth", "3"), p("projectonly", "true"))}  # who calls this?")
        appendLine("   ${u("find-callees", p("method", "handleRequest"), p("maxdepth", "3"), p("projectonly", "false"))}  # what does this call?")
        appendLine("   # ${p("projectonly", "true")} hides JDK/stdlib noise")
        appendLine("   # ${p("maxdepth", "5")} for deeper traversal")
        appendLine()
        appendLine("5. MAP: Understand abstractions")
        appendLine("   ${u("find-interfaces", p("pattern", "Repository"))}")
        appendLine("   # Add ${p("includetest", "true")} to see test fakes and stubs")
        appendLine()
        appendLine("6. MIGRATE: Find external API usage for migration")
        appendLine("   ${u("find-usages", p("ownerClass", "kotlinx.datetime.LocalDate"), p("method", "getMonthNumber"))}")
        appendLine("   ${u("find-usages", p("type", "kotlinx.datetime.Instant"))}")
        appendLine("   # Find all call sites, field accesses, and type references to external types")
        appendLine()
        appendLine("7. ANALYZE: Git history behavioral analysis (no compilation needed)")
        appendLine("   ${u("hotspots")}                     # most-changed files")
        appendLine("   ${u("coupling")}                     # files that change together")
        appendLine("   ${u("code-age")}                          # time since last change per file")
        appendLine("   ${u("authors")}                      # distinct contributors per file")
        appendLine("   ${u("churn")}                        # lines added/deleted per file")
        appendLine("   # All git tasks accept ${p("after", "YYYY-MM-DD")} (default: 1 year ago)")
        appendLine()
        appendLine("--- Task Reference ---")
        appendLine()
        appendLine("  ${t("list-classes")}           List all classes and source files")
        appendLine("  ${t("find-class")}             Find classes by regex       ${p("pattern", "<regex>")}")
        appendLine("  ${t("find-symbol")}            Find methods/fields         ${p("pattern", "<regex>")}")
        appendLine("  ${t("class-detail")}                 Inspect class signature     ${p("pattern", "<regex>")}")
        appendLine("  ${t("find-callers")}               Who calls a method?         ${p("method", "<regex>")}")
        appendLine("  ${t("find-callees")}               What does a method call?    ${p("method", "<regex>")}")
        appendLine("  ${t("find-interfaces")}            Find implementations        ${p("pattern", "<regex>")}")
        appendLine("  ${t("package-deps")}                  Package dependency map      [${p("package", "<regex>")}]")
        appendLine("  ${t("dsm")}                   Dependency Structure Matrix [${p("root-package", "<pkg>")}] [${p("dsm-depth", "N")}] [${p("dsm-html", "<path>")}] [${p("cycles", "true")}]")
        appendLine("  ${t("find-usages")}             Find external API usages    ${p("ownerClass", "<class>")} [${p("method", "<name>")}] or ${p("type", "<class>")}")
        appendLine()
        appendLine("  Git history (no compilation needed):")
        appendLine("  ${t("hotspots")}              Most-changed files          [${p("after", "")}] [${p("min-revs", "")}] [${p("top", "")}]")
        appendLine("  ${t("coupling")}              Files that change together  [${p("after", "")}] [${p("min-shared-revs", "")}] [${p("min-coupling", "")}]")
        appendLine("  ${t("code-age")}                   Time since last change      [${p("after", "")}] [${p("top", "")}]")
        appendLine("  ${t("authors")}               Distinct authors per file   [${p("after", "")}] [${p("min-revs", "")}] [${p("top", "")}]")
        appendLine("  ${t("churn")}                 Lines added/deleted         [${p("after", "")}] [${p("top", "")}]")
        appendLine()
        appendLine("  Help:")
        appendLine("  ${t("help")}                  Full task documentation")
        appendLine("  ${t("agent-help")}             AI agent usage guide")
        appendLine("  ${t("config-help")}            All configuration parameters")
        appendLine()
        appendLine("--- Global Parameters ---")
        appendLine()
        appendLine("  ${p("llm", "true")}                Compact, token-efficient output (all tasks)")
        appendLine("  ${p("format", "json")}             Machine-readable JSON output (all tasks)")
        appendLine("  ${p("projectonly", "true")}         Hide JDK/stdlib (${t("find-callers")}, ${t("find-callees")}, ${t("package-deps")})")
        appendLine("  ${p("maxdepth", "N")}              Max call tree depth (${t("find-callers")}, ${t("find-callees")})")
        appendLine("  ${p("reverse", "true")}            Reverse deps: who depends on me? (${t("package-deps")})")
        appendLine("  ${p("includetest", "true")}        Include test classes (${t("find-interfaces")})")
        appendLine("  ${p("ownerClass", "<class>")}      FQN of type — matches method call and field owners (${t("find-usages")})")
        appendLine("  ${p("type", "<class>")}            Find ALL references: calls, fields, casts, signatures (${t("find-usages")})")
        appendLine("  ${p("root-package", "<pkg>")}      Root package prefix to filter (${t("dsm")})")
        appendLine("  ${p("dsm-depth", "N")}             Package grouping depth (${t("dsm")}, default: 2)")
        appendLine("  ${p("dsm-html", "<path>")}         Write interactive HTML matrix (${t("dsm")})")
        appendLine("  ${p("cycles", "true")}              Show only cyclic dependencies with class-level edges (${t("dsm")})")
        appendLine("  ${p("after", "YYYY-MM-DD")}        Git history window (git tasks, default: 1 year ago)")
        appendLine("  ${pf("no-follow")}               Disable git rename tracking (git tasks, renames tracked by default)")
        appendLine("  ${p("top", "N")}                   Max results (${t("hotspots")}, ${t("code-age")}, ${t("authors")}, ${t("churn")})")
        appendLine("  ${p("min-revs", "N")}              Min revisions (${t("hotspots")}, ${t("authors")})")
        appendLine("  ${p("min-shared-revs", "N")}       Min shared commits (${t("coupling")}, default: 5)")
        appendLine("  ${p("min-coupling", "N")}          Min coupling % (${t("coupling")}, default: 30)")
        appendLine("  ${p("max-changeset-size", "N")}    Skip large commits (${t("coupling")}, default: 30)")
        appendLine()
        appendLine("--- Tips for Optimal Results ---")
        appendLine()
        appendLine("- Always use ${p("llm", "true")}. It maximizes information per token with no decorative formatting.")
        appendLine("  Only omit ${p("llm", "true")} when you need to show output to a human user.")
        appendLine("- Use ${p("format", "json")} only when you need structured data for calculations or aggregations.")
        appendLine("- Use ${p("projectonly", "true")} to cut noise. External call chains are rarely useful.")
        appendLine("- Patterns are Java regex, case-insensitive. Use .* for wildcards.")
        appendLine("- ${t("package-deps")} is the fastest way to understand module/package structure.")
        appendLine("- ${t("class-detail")} is cheaper than reading a source file when you only need the API surface.")
        appendLine("- Chain tasks: find a class, inspect it, then trace its callers — each step narrows context.")
        appendLine("- Results are cached on disk. Repeated runs are fast.")
        appendLine("- Run ${u("help")} for full parameter documentation.")
        appendLine()
        appendLine("--- JSON Schemas ---")
        appendLine()
        appendLine("${t("list-classes")} / ${t("find-class")}:")
        appendLine("  [{\"className\": \"com.example.Foo\", \"sourceFile\": \"Foo.kt\", \"sourcePath\": \"com/example/Foo.kt\"}]")
        appendLine()
        appendLine("${t("find-symbol")}:")
        appendLine("  [{\"package\": \"com.example\", \"class\": \"Service\", \"symbol\": \"doWork\", \"kind\": \"method\", \"sourceFile\": \"Service.kt\"}]")
        appendLine()
        appendLine("${t("class-detail")}:")
        appendLine("  [{\"className\": \"...\", \"sourceFile\": \"...\", \"superClass\": \"...\",")
        appendLine("    \"interfaces\": [\"...\"], \"fields\": [{\"name\": \"...\", \"type\": \"...\"}],")
        appendLine("    \"methods\": [{\"name\": \"...\", \"parameters\": [\"...\"], \"returnType\": \"...\"}]}]")
        appendLine()
        appendLine("${t("find-callers")} / ${t("find-callees")}:")
        appendLine("  [{\"method\": \"com.example.Service.doWork\", \"sourceFile\": \"Service.kt\",")
        appendLine("    \"children\": [{\"method\": \"...\", \"sourceFile\": \"...\", \"children\": [...]}]}]")
        appendLine()
        appendLine("${t("find-interfaces")}:")
        appendLine("  [{\"interface\": \"com.example.Repository\",")
        appendLine("    \"implementors\": [{\"className\": \"com.example.SqlRepo\", \"sourceFile\": \"SqlRepo.kt\"}]}]")
        appendLine()
        appendLine("${t("package-deps")}:")
        appendLine("  [{\"package\": \"com.example.services\", \"dependencies\": [\"com.example.domain\"]}]")
        appendLine("  With ${p("reverse", "true")}: \"dependents\" replaces \"dependencies\"")
        appendLine()
        appendLine("${t("find-usages")}:")
        appendLine("  [{\"callerClass\": \"com.example.MyService\", \"callerMethod\": \"process\",")
        appendLine("    \"targetOwner\": \"kotlinx.datetime.LocalDate\", \"targetMethod\": \"getMonthNumber\",")
        appendLine("    \"kind\": \"method_call\", \"sourceFile\": \"MyService.kt\"}]")
        appendLine()
        appendLine("--- Extracting Output ---")
        appendLine()
        val buildToolNote = when (tool) {
            BuildTool.GRADLE -> "When using ${p("llm", "true")} or ${p("format", "json")}, Gradle mixes its own output (task headers,\nwarnings, build status) into stdout. To handle this, output is wrapped with markers:"
            BuildTool.MAVEN -> "When using ${p("llm", "true")} or ${p("format", "json")}, Maven may mix its own output\ninto stdout. To handle this, output is wrapped with markers:"
        }
        appendLine(buildToolNote)
        appendLine()
        appendLine("  ---CNAV_BEGIN---")
        appendLine("  [{\"className\":\"...\"}]")
        appendLine("  ---CNAV_END---")
        appendLine()
        appendLine("Extract the JSON between markers using sed:")
        appendLine("  ${u("list-classes", p("format", "json"))} 2>/dev/null | sed -n '/---CNAV_BEGIN---/,/---CNAV_END---/{//!p;}'")
        appendLine()
        appendLine("Or define a shell helper to reduce noise:")
        val helperName = "cnav"
        val helperExample = when (tool) {
            BuildTool.GRADLE -> "  $helperName() { ./gradlew \"\$@\" 2>/dev/null | sed -n '/---CNAV_BEGIN---/,/---CNAV_END---/{//!p;}'; }"
            BuildTool.MAVEN -> "  $helperName() { mvn \"\$@\" 2>/dev/null | sed -n '/---CNAV_BEGIN---/,/---CNAV_END---/{//!p;}'; }"
        }
        appendLine(helperExample)
        appendLine()
        appendLine("--- jq Examples (using $helperName helper) ---")
        appendLine()
        appendLine("Extract class names:")
        appendLine("  $helperName ${t("list-classes")} ${p("format", "json")} | jq '.[].className'")
        appendLine()
        appendLine("Find source file for a class:")
        appendLine("  $helperName ${t("find-class")} ${p("pattern", "Service")} ${p("format", "json")} | jq '.[].sourcePath'")
        appendLine()
        appendLine("Get caller method names:")
        appendLine("  $helperName ${t("find-callers")} ${p("method", "save")} ${p("maxdepth", "3")} ${p("format", "json")} | jq '.[].children[].method'")
        appendLine()
        appendLine("List packages that depend on domain:")
        appendLine("  $helperName ${t("package-deps")} ${p("package", "domain")} ${p("reverse", "true")} ${p("format", "json")} | jq '.[].dependents[]'")
        appendLine()
        appendLine("Get interface implementor class names:")
        appendLine("  $helperName ${t("find-interfaces")} ${p("pattern", "Repository")} ${p("format", "json")} | jq '.[].implementors[].className'")
    }
}
