package no.f12.codenavigator

object AgentHelpText {
    fun generate(): String = buildString {
        appendLine("=== code-navigator: AI Agent Guide ===")
        appendLine()
        appendLine("code-navigator is a Gradle plugin that analyzes JVM bytecode and git history.")
        appendLine("It gives you structural and behavioral insight into a codebase without reading source files.")
        appendLine("All tasks support -Pllm=true for compact, token-efficient output.")
        appendLine("All tasks also support -Pformat=json for structured, parseable output.")
        appendLine()
        appendLine("--- Why use this instead of grep? ---")
        appendLine()
        appendLine("Text search (grep, ripgrep) requires iterative discovery. You search for")
        appendLine("\"cache.get(\", find some results, then realize you missed the Kotlin safe-call")
        appendLine("\"cache?.get(\", then extension functions, then delegation patterns. Each iteration")
        appendLine("requires you to know what syntactic variant you haven't tried yet — and you can't")
        appendLine("know what you've missed until you find it by accident.")
        appendLine()
        appendLine("Bytecode analysis sidesteps this entirely. All syntax variants compile to the same")
        appendLine("invocation instruction. One cnavCallers query returns all call sites — complete,")
        appendLine("correct, no false positives, no missed calls.")
        appendLine()
        appendLine("For an agent, each grep iteration is a tool call round-trip. For a human, each is")
        appendLine("a context switch. code-navigator eliminates the iterative discovery loop: you get")
        appendLine("the full call graph from one query.")
        appendLine()
        appendLine("--- Recommended Workflow ---")
        appendLine()
        appendLine("1. ORIENT: Get a high-level view of the codebase")
        appendLine("   ./gradlew cnavDeps                        # package dependency map")
        appendLine("   ./gradlew cnavDsm                         # dependency structure matrix")
        appendLine("   ./gradlew cnavDeps -Pformat=json           # same, as JSON")
        appendLine("   ./gradlew cnavListClasses                  # all classes and source files")
        appendLine()
        appendLine("2. FIND: Locate relevant code")
        appendLine("   ./gradlew cnavFindClass -Ppattern=Service  # find classes by name")
        appendLine("   ./gradlew cnavFindSymbol -Ppattern=reset   # find methods/fields by name")
        appendLine()
        appendLine("3. INSPECT: Understand a class")
        appendLine("   ./gradlew cnavClass -Ppattern=ResetPasswordService")
        appendLine("   # Shows fields, methods, superclass, and implemented interfaces")
        appendLine()
        appendLine("4. TRACE: Follow the call graph")
        appendLine("   ./gradlew cnavCallers -Pmethod=resetPassword -Pmaxdepth=3 -Pprojectonly=true  # who calls this?")
        appendLine("   ./gradlew cnavCallees -Pmethod=handleRequest -Pmaxdepth=3 -Pprojectonly=false  # what does this call?")
        appendLine("   # -Pprojectonly=true hides JDK/stdlib noise")
        appendLine("   # -Pmaxdepth=5 for deeper traversal")
        appendLine()
        appendLine("5. MAP: Understand abstractions")
        appendLine("   ./gradlew cnavInterfaces -Ppattern=Repository")
        appendLine("   # Add -Pincludetest=true to see test fakes and stubs")
        appendLine()
        appendLine("6. ANALYZE: Git history behavioral analysis (no compilation needed)")
        appendLine("   ./gradlew cnavHotspots                     # most-changed files")
        appendLine("   ./gradlew cnavCoupling                     # files that change together")
        appendLine("   ./gradlew cnavAge                          # time since last change per file")
        appendLine("   ./gradlew cnavAuthors                      # distinct contributors per file")
        appendLine("   ./gradlew cnavChurn                        # lines added/deleted per file")
        appendLine("   # All git tasks accept -Pafter=YYYY-MM-DD (default: 1 year ago)")
        appendLine()
        appendLine("--- Task Reference ---")
        appendLine()
        appendLine("  cnavListClasses           List all classes and source files")
        appendLine("  cnavFindClass             Find classes by regex       -Ppattern=<regex>")
        appendLine("  cnavFindSymbol            Find methods/fields         -Ppattern=<regex>")
        appendLine("  cnavClass                 Inspect class signature     -Ppattern=<regex>")
        appendLine("  cnavCallers               Who calls a method?         -Pmethod=<regex>")
        appendLine("  cnavCallees               What does a method call?    -Pmethod=<regex>")
        appendLine("  cnavInterfaces            Find implementations        -Ppattern=<regex>")
        appendLine("  cnavDeps                  Package dependency map      [-Ppackage=<regex>]")
        appendLine("  cnavDsm                   Dependency Structure Matrix [-Proot-package=<pkg>] [-Pdsm-depth=N] [-Pdsm-html=<path>]")
        appendLine()
        appendLine("  Git history (no compilation needed):")
        appendLine("  cnavHotspots              Most-changed files          [-Pafter] [-Pmin-revs] [-Ptop]")
        appendLine("  cnavCoupling              Files that change together  [-Pafter] [-Pmin-shared-revs] [-Pmin-coupling]")
        appendLine("  cnavAge                   Time since last change      [-Pafter] [-Ptop]")
        appendLine("  cnavAuthors               Distinct authors per file   [-Pafter] [-Pmin-revs] [-Ptop]")
        appendLine("  cnavChurn                 Lines added/deleted         [-Pafter] [-Ptop]")
        appendLine()
        appendLine("  Help:")
        appendLine("  cnavHelp                  Full task documentation")
        appendLine("  cnavAgentHelp             AI agent usage guide")
        appendLine("  cnavHelpConfig            All -P configuration parameters")
        appendLine()
        appendLine("--- Global Parameters ---")
        appendLine()
        appendLine("  -Pllm=true                Compact, token-efficient output (all tasks)")
        appendLine("  -Pformat=json             Machine-readable JSON output (all tasks)")
        appendLine("  -Pprojectonly=true         Hide JDK/stdlib (cnavCallers, cnavCallees, cnavDeps)")
        appendLine("  -Pmaxdepth=N              Max call tree depth (cnavCallers, cnavCallees)")
        appendLine("  -Preverse=true            Reverse deps: who depends on me? (cnavDeps)")
        appendLine("  -Pincludetest=true        Include test classes (cnavInterfaces)")
        appendLine("  -Proot-package=<pkg>      Root package prefix to filter (cnavDsm)")
        appendLine("  -Pdsm-depth=N             Package grouping depth (cnavDsm, default: 2)")
        appendLine("  -Pdsm-html=<path>         Write interactive HTML matrix (cnavDsm)")
        appendLine("  -Pafter=YYYY-MM-DD        Git history window (git tasks, default: 1 year ago)")
        appendLine("  -Pno-follow               Disable git rename tracking (git tasks, renames tracked by default)")
        appendLine("  -Ptop=N                   Max results (cnavHotspots, cnavAge, cnavAuthors, cnavChurn)")
        appendLine("  -Pmin-revs=N              Min revisions (cnavHotspots, cnavAuthors)")
        appendLine("  -Pmin-shared-revs=N       Min shared commits (cnavCoupling, default: 5)")
        appendLine("  -Pmin-coupling=N          Min coupling % (cnavCoupling, default: 30)")
        appendLine("  -Pmax-changeset-size=N    Skip large commits (cnavCoupling, default: 30)")
        appendLine()
        appendLine("--- Tips for Optimal Results ---")
        appendLine()
        appendLine("- Always use -Pllm=true. It maximizes information per token with no decorative formatting.")
        appendLine("  Only omit -Pllm=true when you need to show output to a human user.")
        appendLine("- Use -Pformat=json only when you need structured data for calculations or aggregations.")
        appendLine("- Use -Pprojectonly=true to cut noise. External call chains are rarely useful.")
        appendLine("- Patterns are Java regex, case-insensitive. Use .* for wildcards.")
        appendLine("- cnavDeps is the fastest way to understand module/package structure.")
        appendLine("- cnavClass is cheaper than reading a source file when you only need the API surface.")
        appendLine("- Chain tasks: find a class, inspect it, then trace its callers — each step narrows context.")
        appendLine("- Results are cached on disk. Repeated runs are fast (~400ms Gradle overhead).")
        appendLine("- Run ./gradlew cnavHelp for full parameter documentation.")
        appendLine()
        appendLine("--- JSON Schemas ---")
        appendLine()
        appendLine("cnavListClasses / cnavFindClass:")
        appendLine("  [{\"className\": \"com.example.Foo\", \"sourceFile\": \"Foo.kt\", \"sourcePath\": \"com/example/Foo.kt\"}]")
        appendLine()
        appendLine("cnavFindSymbol:")
        appendLine("  [{\"package\": \"com.example\", \"class\": \"Service\", \"symbol\": \"doWork\", \"kind\": \"method\", \"sourceFile\": \"Service.kt\"}]")
        appendLine()
        appendLine("cnavClass:")
        appendLine("  [{\"className\": \"...\", \"sourceFile\": \"...\", \"superClass\": \"...\",")
        appendLine("    \"interfaces\": [\"...\"], \"fields\": [{\"name\": \"...\", \"type\": \"...\"}],")
        appendLine("    \"methods\": [{\"name\": \"...\", \"parameters\": [\"...\"], \"returnType\": \"...\"}]}]")
        appendLine()
        appendLine("cnavCallers / cnavCallees:")
        appendLine("  [{\"method\": \"com.example.Service.doWork\", \"sourceFile\": \"Service.kt\",")
        appendLine("    \"children\": [{\"method\": \"...\", \"sourceFile\": \"...\", \"children\": [...]}]}]")
        appendLine()
        appendLine("cnavInterfaces:")
        appendLine("  [{\"interface\": \"com.example.Repository\",")
        appendLine("    \"implementors\": [{\"className\": \"com.example.SqlRepo\", \"sourceFile\": \"SqlRepo.kt\"}]}]")
        appendLine()
        appendLine("cnavDeps:")
        appendLine("  [{\"package\": \"com.example.services\", \"dependencies\": [\"com.example.domain\"]}]")
        appendLine("  With -Preverse=true: \"dependents\" replaces \"dependencies\"")
        appendLine()
        appendLine("--- Extracting Output ---")
        appendLine()
        appendLine("When using -Pllm=true or -Pformat=json, Gradle mixes its own output (task headers,")
        appendLine("warnings, build status) into stdout. To handle this, output is wrapped with markers:")
        appendLine()
        appendLine("  ---CNAV_BEGIN---")
        appendLine("  [{\"className\":\"...\"}]")
        appendLine("  ---CNAV_END---")
        appendLine()
        appendLine("Extract the JSON between markers using sed:")
        appendLine("  ./gradlew cnavListClasses -Pformat=json 2>/dev/null | sed -n '/---CNAV_BEGIN---/,/---CNAV_END---/{//!p;}'")
        appendLine()
        appendLine("Or define a shell helper to reduce noise:")
        appendLine("  cnav() { ./gradlew \"\$@\" 2>/dev/null | sed -n '/---CNAV_BEGIN---/,/---CNAV_END---/{//!p;}'; }")
        appendLine()
        appendLine("--- jq Examples (using cnav helper) ---")
        appendLine()
        appendLine("Extract class names:")
        appendLine("  cnav cnavListClasses -Pformat=json | jq '.[].className'")
        appendLine()
        appendLine("Find source file for a class:")
        appendLine("  cnav cnavFindClass -Ppattern=Service -Pformat=json | jq '.[].sourcePath'")
        appendLine()
        appendLine("Get caller method names:")
        appendLine("  cnav cnavCallers -Pmethod=save -Pmaxdepth=3 -Pformat=json | jq '.[].children[].method'")
        appendLine()
        appendLine("List packages that depend on domain:")
        appendLine("  cnav cnavDeps -Ppackage=domain -Preverse=true -Pformat=json | jq '.[].dependents[]'")
        appendLine()
        appendLine("Get interface implementor class names:")
        appendLine("  cnav cnavInterfaces -Ppattern=Repository -Pformat=json | jq '.[].implementors[].className'")
    }
}
