package no.f12.codenavigator

object ConfigHelpText {
    fun generate(): String = buildString {
        appendLine("=== code-navigator: Configuration Reference ===")
        appendLine()
        appendLine("All parameters are passed as Gradle project properties (-P flags).")
        appendLine("Example: ./gradlew cnavFindClass -Ppattern=Service -Pformat=json")
        appendLine()
        appendLine("--- Global Parameters (all tasks) ---")
        appendLine()
        appendLine("  -Pformat=json             Output as machine-readable JSON")
        appendLine("  -Pllm=true                Output in compact, token-efficient LLM format")
        appendLine()
        appendLine("--- Navigation Tasks ---")
        appendLine()
        appendLine("  -Ppattern=<regex>         Class/symbol regex (cnavFindClass, cnavFindSymbol, cnavClass, cnavInterfaces)")
        appendLine("  -Pmethod=<regex>          Method regex (cnavCallers, cnavCallees)")
        appendLine("  -Pmaxdepth=<N>            Max call tree depth (cnavCallers, cnavCallees)")
        appendLine("  -Pprojectonly=true        Hide JDK/stdlib classes (cnavCallers, cnavCallees, cnavDeps)")
        appendLine("  -Preverse=true            Show reverse dependencies (cnavDeps)")
        appendLine("  -Ppackage=<regex>         Filter packages by regex (cnavDeps)")
        appendLine("  -Pincludetest=true        Include test source set (cnavInterfaces)")
        appendLine()
        appendLine("--- DSM (Dependency Structure Matrix) ---")
        appendLine()
        appendLine("  -Proot-package=<pkg>      Only include packages under this prefix (cnavDsm, default: all)")
        appendLine("  -Pdsm-depth=<N>           Package grouping depth (cnavDsm, default: 2)")
        appendLine("  -Pdsm-html=<path>         Write interactive HTML matrix to file (cnavDsm)")
        appendLine()
        appendLine("--- Git History Analysis ---")
        appendLine()
        appendLine("  -Pafter=YYYY-MM-DD        Only consider commits after this date (default: 1 year ago)")
        appendLine("  -Pno-follow               Disable git rename tracking (renames tracked by default)")
        appendLine("  -Ptop=<N>                 Max results (cnavHotspots, cnavAge, cnavAuthors, cnavChurn, default: 50)")
        appendLine("  -Pmin-revs=<N>            Min revisions to include (cnavHotspots, cnavAuthors, default: 1)")
        appendLine("  -Pmin-shared-revs=<N>     Min shared commits (cnavCoupling, default: 5)")
        appendLine("  -Pmin-coupling=<N>        Min coupling degree % (cnavCoupling, default: 30)")
        appendLine("  -Pmax-changeset-size=<N>  Skip commits touching more files (cnavCoupling, default: 30)")
    }
}
