package no.f12.codenavigator

object HelpText {
    fun generate(tool: BuildTool = BuildTool.GRADLE): String = buildString {
        val t = { goal: String -> tool.taskName(goal) }
        val p = { name: String, value: String -> tool.param(name, value) }
        val pf = { name: String -> tool.paramFlag(name) }
        fun u(goal: String, vararg params: String) = tool.usage(goal, *params)
        fun pd(param: ParamDef<*>, description: String) = paramDoc(param, tool, description)

        appendLine("=== code-navigator plugin ===")
        appendLine()
        appendLine("All tasks support ${p("format", "json")} for machine-readable JSON output.")
        appendLine()
        appendLine("--- Pattern Matching ---")
        appendLine()
        appendLine("All pattern parameters are Java regex, case-insensitive, and matched as substrings.")
        appendLine("Simple class names work because of substring matching: 'Owner' matches")
        appendLine("'org.springframework.samples.petclinic.owner.Owner'.")
        appendLine("FQN patterns with escaped dots also work: 'owner\\.Owner' matches the full path.")
        appendLine()
        appendLine("CamelCase shorthand: at camelCase boundaries, .* is inserted automatically.")
        appendLine("  OwnCont  →  Own.*Cont  (matches OwnerController, OwnerContentService, etc.)")
        appendLine()
        appendLine("Parameters with camelCase enhancement: pattern, owner-class, type")
        appendLine("  These auto-expand camelCase boundaries into .* wildcards.")
        appendLine()
        appendLine("Plain regex parameters (no camelCase expansion): method, field, filter, exclude")
        appendLine("  These are matched as-is. The find-string-constant 'pattern' is also plain regex.")
        appendLine()
        appendLine("Available tasks:")
        appendLine()
        appendLine("  ${t("help")}")
        appendLine("    Shows this help text.")
        appendLine("    Usage: ${u("help")}")
        appendLine()
        appendLine("  ${t("list-classes")}")
        appendLine("    Lists all classes in the project and their source files.")
        appendLine("    Scans the compiled main source set.")
        appendLine("    Usage: ${u("list-classes")}")
        appendLine()
        appendLine("  ${t("find-class")}")
        appendLine("    Searches for classes matching a regex pattern.")
        appendLine("    Matches against both class name and source file path (case-insensitive).")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against class names and source paths")}")
        appendLine("    Usage: ${u("find-class", p("pattern", "Service"))}")
        appendLine("    Usage: ${u("find-class", p("pattern", "\".*Reset.*\""))}")
        appendLine("    Usage: ${u("find-class", p("pattern", "\"domain\\\\..*\""))}")
        appendLine()
        appendLine("  ${t("find-symbol")}")
        appendLine("    Searches for symbols (methods, fields) matching a regex pattern.")
        appendLine("    Matches against package, class name, symbol name, and source file (case-insensitive).")
        appendLine("    Filters out constructors, synthetic methods, property accessors, and data class generated methods.")
        appendLine("    Output columns: Package | Class | Symbol | Kind | Source File")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against symbol information")}")
        appendLine("    Usage: ${u("find-symbol", p("pattern", "resetPassword"))}")
        appendLine("    Usage: ${u("find-symbol", p("pattern", "\".*Service.*\""))}")
        appendLine("    Usage: ${u("find-symbol", p("pattern", "\"find.*\""))}")
        appendLine()
        appendLine("  ${t("find-callers")}")
        appendLine("    Shows who calls a given method, displayed as an indented tree.")
        appendLine("    Builds a call graph from compiled code, then walks callers transitively.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.CALL_PATTERN, "Regex to match against Class.method names")}")
        appendLine("      ${pd(TaskRegistry.MAXDEPTH, "Maximum depth of caller tree")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY, "Filter to project classes only, hiding JDK/stdlib noise")}")
        appendLine("      ${pd(TaskRegistry.FILTER_SYNTHETIC, "Set false to include equals, hashCode, copy, componentN, etc.")}")
        appendLine("      ${pd(TaskRegistry.PROD_ONLY, "Show only callers from production source set")}")
        appendLine("      ${pd(TaskRegistry.TEST_ONLY, "Show only callers from test source set")}")
        appendLine("    Usage: ${u("find-callers", p("pattern", "resetPassword"), p("maxdepth", "3"))}")
        appendLine("    Usage: ${u("find-callers", p("pattern", "\".*Service\\\\.find.*\""), p("maxdepth", "5"))}")
        appendLine("    Usage: ${u("find-callers", p("pattern", "\"Repo\\\\.save\""), p("maxdepth", "5"), p("project-only", "true"))}")
        appendLine()
        appendLine("  ${t("find-callees")}")
        appendLine("    Shows what a method calls, displayed as an indented tree.")
        appendLine("    Builds a call graph from compiled code, then walks callees transitively.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.CALL_PATTERN, "Regex to match against Class.method names")}")
        appendLine("      ${pd(TaskRegistry.MAXDEPTH, "Maximum depth of callee tree")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY, "Filter to project classes only, hiding JDK/stdlib noise")}")
        appendLine("      ${pd(TaskRegistry.FILTER_SYNTHETIC, "Set false to include equals, hashCode, copy, componentN, etc.")}")
        appendLine("      ${pd(TaskRegistry.PROD_ONLY, "Show only callees from production source set")}")
        appendLine("      ${pd(TaskRegistry.TEST_ONLY, "Show only callees from test source set")}")
        appendLine("    Usage: ${u("find-callees", p("pattern", "resetPassword"), p("maxdepth", "3"))}")
        appendLine("    Usage: ${u("find-callees", p("pattern", "\".*Controller\\\\.handle.*\""), p("maxdepth", "5"))}")
        appendLine("    Usage: ${u("find-callees", p("pattern", "\"Service\\\\.create\""), p("maxdepth", "5"), p("project-only", "true"))}")
        appendLine()
        appendLine("  ${t("class-detail")}")
        appendLine("    Shows class signature: fields, methods, superclass, and implemented interfaces.")
        appendLine("    Filters out constructors, synthetic methods, property accessors, and data class boilerplate.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against class names")}")
        appendLine("    Usage: ${u("class-detail", p("pattern", "ResetPasswordService"))}")
        appendLine("    Usage: ${u("class-detail", p("pattern", "\".*Client\""))}")
        appendLine("    Usage: ${u("class-detail", p("pattern", "\"domain\\\\.DomainError\""))}")
        appendLine()
        appendLine("  ${t("find-interfaces")}")
        appendLine("    Finds classes that implement a given interface.")
        appendLine("    Builds an interface-to-implementors map from compiled code.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against interface names")}")
        appendLine("      ${pd(TaskRegistry.FIND_INTERFACES.paramByName("include-test"), "Include test source set to find test fakes/stubs")}")
        appendLine("    Usage: ${u("find-interfaces", p("pattern", "Repository"))}")
        appendLine("    Usage: ${u("find-interfaces", p("pattern", "\".*Client\""))}")
        appendLine("    Usage: ${u("find-interfaces", p("pattern", "\"services\\\\.interfaces\\\\..*\""))}")
        appendLine("    Usage: ${u("find-interfaces", p("pattern", "Repository"), p("include-test", "true"))}")
        appendLine()
        appendLine("  ${t("type-hierarchy")}")
        appendLine("    Shows the type hierarchy for classes matching a pattern.")
        appendLine("    Walks supertypes upward (superclass chain + interfaces, recursively) and")
        appendLine("    shows implementors downward (classes implementing matched interfaces).")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against class/interface names")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY, "Filter to project classes only")}")
        appendLine("    Usage: ${u("type-hierarchy", p("pattern", "Service"))}")
        appendLine("    Usage: ${u("type-hierarchy", p("pattern", "\".*Repository\""))}")
        appendLine("    Usage: ${u("type-hierarchy", p("pattern", "\"domain\\\\..*\""), p("project-only", "true"))}")
        appendLine()
        appendLine("  ${t("package-deps")}")
        appendLine("    Shows package-level dependencies — which packages call into which other packages.")
        appendLine("    Aggregates the call graph by package, excluding self-dependencies.")
        appendLine("    Without ${p("package", "<regex>")}, shows all packages. With ${p("package", "<regex>")}, filters to matching packages.")
        appendLine("    With ${p("reverse", "true")}, shows reverse dependencies (who depends on each package).")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PACKAGE_DEPS.paramByName("package"), "Regex to match against package names")}")
        appendLine("      ${pd(TaskRegistry.PACKAGE_DEPS.paramByName("reverse"), "Show reverse dependencies (incoming instead of outgoing)")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY, "Filter to project classes only, hiding JDK/stdlib noise")}")
        appendLine("    Usage: ${u("package-deps")}")
        appendLine("    Usage: ${u("package-deps", p("package", "services"))}")
        appendLine("    Usage: ${u("package-deps", p("package", "\"ktor\\\\.routes\""))}")
        appendLine("    Usage: ${u("package-deps", p("reverse", "true"))}")
        appendLine("    Usage: ${u("package-deps", p("package", "domain"), p("reverse", "true"))}")
        appendLine("    Usage: ${u("package-deps", p("project-only", "true"))}")
        appendLine()
        appendLine("  ${t("find-usages")}")
        appendLine("    Finds project references to external types or methods.")
        appendLine("    Scans compiled code for method calls, field accesses, and type references")
        appendLine("    matching the specified owner-class/method or type. Owner-aware — distinguishes")
        appendLine("    same-named methods on different types. Finds Kotlin property accessors by")
        appendLine("    their compiled name (e.g., getMonthNumber for .monthNumber).")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.FIND_USAGES.paramByName("owner-class"), "FQN of type — matches method call and field owners")}")
        appendLine("      ${pd(TaskRegistry.METHOD, "Specific method/field name on the owner")}")
        appendLine("      ${pd(TaskRegistry.FIND_USAGES.paramByName("field"), "Field/property name — also matches getter/setter/is-prefixed accessors")}")
        appendLine("      ${pd(TaskRegistry.FIND_USAGES.paramByName("type"), "Find ALL references to a class: calls, fields, casts, signatures")}")
        appendLine("      ${pd(TaskRegistry.FIND_USAGES.paramByName("outside-package"), "Exclude callers inside this package (show only external usages)")}")
        appendLine("      ${pd(TaskRegistry.PROD_ONLY, "Show only usages from production source set")}")
        appendLine("      ${pd(TaskRegistry.TEST_ONLY, "Show only usages from test source set")}")
        appendLine("      * Provide either 'owner-class' or 'type'. Use 'type' for comprehensive search.")
        appendLine("      * 'method' and 'field' are mutually exclusive. 'field' requires 'owner-class'.")
        appendLine("    Usage: ${u("find-usages", p("owner-class", "kotlinx.datetime.LocalDate"), p("method", "getMonthNumber"))}")
        appendLine("    Usage: ${u("find-usages", p("owner-class", "kotlinx.datetime.Clock"))}")
        appendLine("    Usage: ${u("find-usages", p("owner-class", "com.example.Config"), p("field", "timeout"))}")
        appendLine("    Usage: ${u("find-usages", p("type", "kotlinx.datetime.Instant"))}")
        appendLine("    Usage: ${u("find-usages", p("type", "kotlinx.datetime.Instant"), p("outside-package", "com.example.datetime"))}")
        appendLine()
        appendLine("  ${t("dsm")}")
        appendLine("    Shows a Dependency Structure Matrix (DSM) — a compact grid view of inter-package")
        appendLine("    dependencies. Row depends on column; cells show reference counts. Highlights cyclic")
        appendLine("    dependencies with class-level detail.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.DSM.paramByName("root-package"), "Only include packages under this prefix")}")
        appendLine("      ${pd(TaskRegistry.DSM.paramByName("dsm-depth"), "Package depth to group by")}")
        appendLine("      ${pd(TaskRegistry.DSM.paramByName("dsm-html"), "Write interactive HTML matrix to file")}")
        appendLine("      ${pd(TaskRegistry.DSM.paramByName("cycles"), "Show only cyclic dependencies with class-level edges")}")
        appendLine("      ${pd(TaskRegistry.DSM.paramByName("cycle"), "Show only the cycle between two specific packages")}")
        appendLine("    Usage: ${u("dsm")}")
        appendLine("    Usage: ${u("dsm", p("root-package", "com.example"), p("dsm-depth", "3"))}")
        appendLine("    Usage: ${u("dsm", p("dsm-html", "build/dsm.html"))}")
        appendLine("    Usage: ${u("dsm", p("cycles", "true"))}")
        appendLine("    Usage: ${u("dsm", p("cycle", "api,service"))}")
        appendLine()
        appendLine("  ${t("cycles")}")
        appendLine("    Detects dependency cycles using Tarjan's SCC (Strongly Connected Components) algorithm.")
        appendLine("    Unlike '${t("dsm")} ${p("cycles", "true")}' which only finds pairwise bidirectional edges (A<->B),")
        appendLine("    this finds true multi-node cycles (A->B->C->A). Shows class-level edges for each cycle.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.CYCLE_DETECTION.paramByName("root-package"), "Only include packages under this prefix")}")
        appendLine("      ${pd(TaskRegistry.CYCLE_DETECTION.paramByName("dsm-depth"), "Package depth to group by")}")
        appendLine("    Usage: ${u("cycles")}")
        appendLine("    Usage: ${u("cycles", p("root-package", "com.example"), p("dsm-depth", "3"))}")
        appendLine()
        appendLine("  ${t("rank")}")
        appendLine("    Ranks types by structural importance using PageRank on the call graph.")
        appendLine("    Types that are called by many important types score higher. Useful for")
        appendLine("    identifying core abstractions, god classes, and critical dependencies.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.TOP, "Maximum results to return")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY, "Filter to project classes only")}")
        appendLine("      ${pd(TaskRegistry.PROD_ONLY, "Show only types from production source set")}")
        appendLine("      ${pd(TaskRegistry.TEST_ONLY, "Show only types from test source set")}")
        appendLine("    Usage: ${u("rank")}")
        appendLine("    Usage: ${u("rank", p("top", "20"))}")
        appendLine("    Usage: ${u("rank", p("project-only", "false"))}")
        appendLine()
        appendLine("  ${t("dead")}")
        appendLine("    Finds potential dead code — classes and methods never referenced by other project code.")
        appendLine("    Reports classes with no incoming type-level references and methods with no cross-class callers.")
        appendLine("    Kotlin noise (data class boilerplate, companion objects, coroutine inner classes,")
        appendLine("    bridge methods, static initializers) is automatically filtered out.")
        appendLine("    Results are 'potential' dead code — reflection-based usage cannot be detected statically.")
        appendLine("    Each result includes a confidence level:")
        appendLine("      HIGH   = unreferenced in both production and test code")
        appendLine("      MEDIUM = unreferenced in production but referenced in test code")
        appendLine("      LOW    = has annotations (likely invoked via reflection/framework)")
        appendLine("    Framework presets distinguish entry-point vs modifier annotations:")
        appendLine("      Entry-point annotations (e.g. @GetMapping, @Scheduled) → excluded from results.")
        appendLine("      Modifier annotations (e.g. @Transactional, @Cacheable) → reported with LOW confidence.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.DEAD.paramByName("filter"), "Only show results matching this regex")}")
        appendLine("      ${pd(TaskRegistry.DEAD.paramByName("exclude"), "Exclude results matching this regex (e.g. entry points, generated packages)")}")
        appendLine("      ${pd(TaskRegistry.DEAD.paramByName("classes-only"), "Show only unreferenced classes, skip dead methods")}")
        appendLine("      ${pd(TaskRegistry.DEAD.paramByName("exclude-annotated"), "Exclude classes/methods bearing these annotations (simple names, comma-separated)")}")
        appendLine("      ${pd(TaskRegistry.DEAD.paramByName("prod-only"), "Show only items unreferenced in both production and test code (hides test-only references)")}")
        appendLine("      ${pd(TaskRegistry.DEAD.paramByName("exclude-framework"), "Disable framework preset (all active by default). Use ALL to disable all.")}")
        appendLine("    Usage: ${u("dead")}")
        appendLine("    Usage: ${u("dead", p("filter", "\"service\""))}")
        appendLine("    Usage: ${u("dead", p("exclude", "\"Main|Test|Application\""))}")
        appendLine("    Usage: ${u("dead", p("exclude", "\"com\\\\.example\\\\.grpc\""))}  # exclude generated packages")
        appendLine("    Usage: ${u("dead", p("classes-only", "true"))}")
        appendLine("    Usage: ${u("dead", p("exclude-annotated", "\"RestController,Scheduled\""))}")
        appendLine("    Usage: ${u("dead", p("prod-only", "true"))}")
        appendLine("    Usage: ${u("dead", p("exclude-framework", "spring"))}")
        appendLine("    Usage: ${u("dead", p("exclude-framework", "ALL"))}")
        appendLine()
        appendLine("  ${t("find-string-constant")}")
        appendLine("    Searches for string constants in compiled code matching a regex pattern.")
        appendLine("    Finds hardcoded strings — useful for")
        appendLine("    finding URLs, SQL fragments, configuration keys, log messages, and other literals.")
        appendLine("    Pattern matching is case-insensitive.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.FIND_STRING_CONSTANT.paramByName("pattern"), "Regex to match against string constant values")}")
        appendLine("    Usage: ${u("find-string-constant", p("pattern", "\"http://\""))}")
        appendLine("    Usage: ${u("find-string-constant", p("pattern", "\"SELECT.*FROM\""))}")
        appendLine("    Usage: ${u("find-string-constant", p("pattern", "\"password|secret|key\""))}")
        appendLine()
        appendLine("  ${t("annotations")}")
        appendLine("    Finds classes and methods annotated with names matching a regex pattern.")
        appendLine("    Scans class-level annotations by default. Use ${p("methods", "true")} to also search")
        appendLine("    method-level annotations.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against annotation simple names")}")
        appendLine("      ${pd(TaskRegistry.ANNOTATIONS.paramByName("methods"), "Also search method-level annotations")}")
        appendLine("    Usage: ${u("annotations", p("pattern", "RestController"))}")
        appendLine("    Usage: ${u("annotations", p("pattern", "\".*Mapping\""), p("methods", "true"))}")
        appendLine("    Usage: ${u("annotations", p("pattern", "Scheduled"), p("methods", "true"))}")
        appendLine()
        appendLine("  ${t("complexity")}")
        appendLine("    Shows fan-in/fan-out complexity for classes matching a regex pattern.")
        appendLine("    Fan-out: how many calls go from this class to other classes (outgoing coupling).")
        appendLine("    Fan-in: how many calls come into this class from other classes (incoming coupling).")
        appendLine("    Without ${TaskRegistry.PATTERN.render(tool)}, shows all project classes sorted by fan-out descending.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Class name regex to analyze")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY, "Filter to project classes only")}")
        appendLine("      ${pd(TaskRegistry.COMPLEXITY.paramByName("detail"), "Show individual call details")}")
        appendLine("      ${pd(TaskRegistry.COLLAPSE_LAMBDAS, "Set false to show lambda classes separately")}")
        appendLine("      ${pd(TaskRegistry.TOP, "Maximum results to return")}")
        appendLine("      ${pd(TaskRegistry.PROD_ONLY, "Show only classes from production source set")}")
        appendLine("      ${pd(TaskRegistry.TEST_ONLY, "Show only classes from test source set")}")
        appendLine("    Usage: ${u("complexity")}")
        appendLine("    Usage: ${u("complexity", p("pattern", "Service"))}")
        appendLine("    Usage: ${u("complexity", p("pattern", "\".*Controller\""), p("project-only", "false"))}")
        appendLine("    Usage: ${u("complexity", p("pattern", "\"domain\\\\..*\""), p("detail", "true"))}")
        appendLine()
        appendLine("  ${t("metrics")}")
        appendLine("    Quick project health snapshot combining structural analysis and git history.")
        appendLine("    Shows: total classes, packages, average fan-in/fan-out, cycle count,")
        appendLine("    dead classes/methods, and top hotspots.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER, "Only consider commits after this date")}")
        appendLine("      ${pd(TaskRegistry.TOP, "Number of hotspots to show")}")
        appendLine("      ${pd(TaskRegistry.METRICS.paramByName("root-package"), "Root package prefix for cycle detection")}")
        appendLine("      ${pd(TaskRegistry.NO_FOLLOW, "Disable git rename tracking")}")
        appendLine("    Usage: ${u("metrics")}")
        appendLine("    Usage: ${u("metrics", p("top", "10"), p("after", "2024-01-01"))}")
        appendLine("    Usage: ${u("metrics", p("root-package", "com.example"))}")
        appendLine()
        appendLine("  ${t("changed-since")}")
        appendLine("    Shows the blast radius of changes since a git ref — finds changed source files,")
        appendLine("    maps them to compiled classes, and shows their callers (who is affected).")
        appendLine("    Requires both git (to find changed files) and compilation (to resolve call graph).")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.REF, "Git ref to compare against (branch, tag, or commit SHA)")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY_ON, "Filter callers to project classes only")}")
        appendLine("    Usage: ${u("changed-since", p("ref", "main"))}")
        appendLine("    Usage: ${u("changed-since", p("ref", "v1.2.0"))}")
        appendLine("    Usage: ${u("changed-since", p("ref", "HEAD~5"))}")
        appendLine()
        appendLine("  ${t("agent-help")}")
        appendLine("    Shows detailed instructions for AI coding agents on how to use code-navigator effectively.")
        appendLine("    Includes recommended workflows, task selection guidance, and tips for optimal results.")
        appendLine("    Usage: ${u("agent-help")}")
        appendLine()
        appendLine("  ${t("config-help")}")
        appendLine("    Lists all available configuration parameters with defaults")
        appendLine("    and which tasks they apply to.")
        appendLine("    Usage: ${u("config-help")}")
        appendLine()
        appendLine("--- Git History Analysis Tasks ---")
        appendLine()
        appendLine("These tasks analyze git history and do NOT require compilation.")
        appendLine("All share the parameter: ${TaskRegistry.AFTER.render(tool)} (default: ${TaskRegistry.AFTER.defaultValue})")
        appendLine("Git rename tracking is enabled by default (-M flag). Use ${TaskRegistry.NO_FOLLOW.render(tool)} to disable it.")
        appendLine()
        appendLine("  ${t("hotspots")}")
        appendLine("    Ranks files by change frequency. The most-changed files are where development")
        appendLine("    effort concentrates — priority refactoring targets if they also have structural problems.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER, "Only consider commits after this date")}")
        appendLine("      ${pd(TaskRegistry.MIN_REVS, "Minimum revisions to include")}")
        appendLine("      ${pd(TaskRegistry.TOP, "Maximum results to return")}")
        appendLine("    Usage: ${u("hotspots")}")
        appendLine("    Usage: ${u("hotspots", p("after", "2024-01-01"), p("min-revs", "5"), p("top", "20"))}")
        appendLine()
        appendLine("  ${t("coupling")}")
        appendLine("    Finds files that change together in the same commits — implicit dependencies invisible")
        appendLine("    in call graphs. Complements structural ${t("package-deps")} with behavioral coupling data.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER, "Only consider commits after this date")}")
        appendLine("      ${pd(TaskRegistry.COUPLING.paramByName("min-shared-revs"), "Minimum shared commits to report")}")
        appendLine("      ${pd(TaskRegistry.COUPLING.paramByName("min-coupling"), "Minimum coupling degree %")}")
        appendLine("      ${pd(TaskRegistry.COUPLING.paramByName("max-changeset-size"), "Skip commits touching more files")}")
        appendLine("      ${pd(TaskRegistry.TOP, "Maximum results to return")}")
        appendLine("    Usage: ${u("coupling")}")
        appendLine("    Usage: ${u("coupling", p("min-shared-revs", "10"), p("min-coupling", "50"))}")
        appendLine()
        appendLine("  ${t("code-age")}")
        appendLine("    Measures time since last modification per file. Stable old code is good;")
        appendLine("    frequently-changing old code with structural problems is a hotspot.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER, "Only consider commits after this date")}")
        appendLine("      ${pd(TaskRegistry.TOP, "Maximum results to return")}")
        appendLine("    Usage: ${u("code-age")}")
        appendLine("    Usage: ${u("code-age", p("after", "2023-01-01"), p("top", "20"))}")
        appendLine()
        appendLine("  ${t("authors")}")
        appendLine("    Number of distinct contributors per file. More developers on a module means")
        appendLine("    larger communication challenges. High author counts correlate with defects.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER, "Only consider commits after this date")}")
        appendLine("      ${pd(TaskRegistry.MIN_REVS, "Minimum revisions to include")}")
        appendLine("      ${pd(TaskRegistry.TOP, "Maximum results to return")}")
        appendLine("    Usage: ${u("authors")}")
        appendLine("    Usage: ${u("authors", p("min-revs", "3"), p("top", "20"))}")
        appendLine()
        appendLine("  ${t("churn")}")
        appendLine("    Measures lines added/deleted per file. Pre-release churn is a good predictor")
        appendLine("    of post-release defects.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER, "Only consider commits after this date")}")
        appendLine("      ${pd(TaskRegistry.TOP, "Maximum results to return")}")
        appendLine("    Usage: ${u("churn")}")
        appendLine("    Usage: ${u("churn", p("after", "2024-06-01"), p("top", "30"))}")
        appendLine()
        appendLine("If you are an AI coding agent, run ${u("agent-help")} for optimized guidance.")
    }

    private fun paramDoc(param: ParamDef<*>, tool: BuildTool, description: String): String {
        val rendered = param.render(tool)
        val annotation = when {
            param.defaultValue != null -> "(optional, default: ${param.defaultValue})"
            param.flag -> "(optional)"
            else -> "(required)"
        }
        return "$rendered  $annotation $description"
    }
}

