package no.f12.codenavigator

object HelpText {
    fun generate(tool: BuildTool = BuildTool.GRADLE): String = buildString {
        val t = { goal: String -> tool.taskName(goal) }
        val p = { name: String, value: String -> tool.param(name, value) }
        val pf = { name: String -> tool.paramFlag(name) }
        fun u(goal: String, vararg params: String) = tool.usage(goal, *params)
        fun pd(param: ParamDef, description: String) = paramDoc(param, tool, description)

        appendLine("=== code-navigator plugin ===")
        appendLine()
        appendLine("All tasks support ${p("format", "json")} for machine-readable JSON output.")
        appendLine()
        appendLine("Available tasks:")
        appendLine()
        appendLine("  ${t("help")}")
        appendLine("    Shows this help text.")
        appendLine("    Usage: ${u("help")}")
        appendLine()
        appendLine("  ${t("list-classes")}")
        appendLine("    Lists all classes in the project and their source files.")
        appendLine("    Scans compiled bytecode from the main source set.")
        appendLine("    Usage: ${u("list-classes")}")
        appendLine()
        appendLine("  ${t("find-class")}")
        appendLine("    Searches for classes matching a regex pattern.")
        appendLine("    Matches against both class name and source file path (case-insensitive).")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against class names and source paths")}")
        appendLine("    Usage: ${u("find-class", p("pattern", "Service"))}")
        appendLine("    Usage: ${u("find-class", p("pattern", "\".*Reset.*\""))}")
        appendLine("    Usage: ${u("find-class", p("pattern", "\"domain\\\\..*\""))}")
        appendLine()
        appendLine("  ${t("find-symbol")}")
        appendLine("    Searches for symbols (methods, fields) matching a regex pattern.")
        appendLine("    Matches against package, class name, symbol name, and source file (case-insensitive).")
        appendLine("    Filters out constructors, synthetic methods, property accessors, and data class generated methods.")
        appendLine("    Output columns: Package | Class | Symbol | Kind | Source File")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against symbol information")}")
        appendLine("    Usage: ${u("find-symbol", p("pattern", "resetPassword"))}")
        appendLine("    Usage: ${u("find-symbol", p("pattern", "\".*Service.*\""))}")
        appendLine("    Usage: ${u("find-symbol", p("pattern", "\"find.*\""))}")
        appendLine()
        appendLine("  ${t("find-callers")}")
        appendLine("    Shows who calls a given method, displayed as an indented tree.")
        appendLine("    Scans compiled bytecode to build a call graph, then walks callers transitively.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.METHOD, "Regex to match against Class.method names")}")
        appendLine("      ${pd(TaskRegistry.MAXDEPTH, "Maximum depth of caller tree")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY, "Filter to project classes only, hiding JDK/stdlib noise")}")
        appendLine("    Usage: ${u("find-callers", p("method", "resetPassword"), p("maxdepth", "3"))}")
        appendLine("    Usage: ${u("find-callers", p("method", "\".*Service\\\\.find.*\""), p("maxdepth", "5"))}")
        appendLine("    Usage: ${u("find-callers", p("method", "\"Repo\\\\.save\""), p("maxdepth", "5"), p("projectonly", "true"))}")
        appendLine()
        appendLine("  ${t("find-callees")}")
        appendLine("    Shows what a method calls, displayed as an indented tree.")
        appendLine("    Scans compiled bytecode to build a call graph, then walks callees transitively.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.METHOD, "Regex to match against Class.method names")}")
        appendLine("      ${pd(TaskRegistry.MAXDEPTH, "Maximum depth of callee tree")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY, "Filter to project classes only, hiding JDK/stdlib noise")}")
        appendLine("    Usage: ${u("find-callees", p("method", "resetPassword"), p("maxdepth", "3"))}")
        appendLine("    Usage: ${u("find-callees", p("method", "\".*Controller\\\\.handle.*\""), p("maxdepth", "5"))}")
        appendLine("    Usage: ${u("find-callees", p("method", "\"Service\\\\.create\""), p("maxdepth", "5"), p("projectonly", "true"))}")
        appendLine()
        appendLine("  ${t("class-detail")}")
        appendLine("    Shows class signature: fields, methods, superclass, and implemented interfaces.")
        appendLine("    Filters out constructors, synthetic methods, property accessors, and data class boilerplate.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against class names")}")
        appendLine("    Usage: ${u("class-detail", p("pattern", "ResetPasswordService"))}")
        appendLine("    Usage: ${u("class-detail", p("pattern", "\".*Client\""))}")
        appendLine("    Usage: ${u("class-detail", p("pattern", "\"domain\\\\.DomainError\""))}")
        appendLine()
        appendLine("  ${t("find-interfaces")}")
        appendLine("    Finds classes that implement a given interface.")
        appendLine("    Scans compiled bytecode to build an interface-to-implementors map.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against interface names")}")
        appendLine("      ${pd(TaskRegistry.FIND_INTERFACES.paramByName("includetest"), "Include test source set to find test fakes/stubs")}")
        appendLine("    Usage: ${u("find-interfaces", p("pattern", "Repository"))}")
        appendLine("    Usage: ${u("find-interfaces", p("pattern", "\".*Client\""))}")
        appendLine("    Usage: ${u("find-interfaces", p("pattern", "\"services\\\\.interfaces\\\\..*\""))}")
        appendLine("    Usage: ${u("find-interfaces", p("pattern", "Repository"), p("includetest", "true"))}")
        appendLine()
        appendLine("  ${t("package-deps")}")
        appendLine("    Shows package-level dependencies — which packages call into which other packages.")
        appendLine("    Aggregates the call graph by package, excluding self-dependencies.")
        appendLine("    Without ${p("package", "<regex>")}, shows all packages. With ${p("package", "<regex>")}, filters to matching packages.")
        appendLine("    With ${p("reverse", "true")}, shows reverse dependencies (who depends on each package).")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PACKAGE_DEPS.paramByName("package"), "Regex to match against package names")}")
        appendLine("      ${pd(TaskRegistry.PACKAGE_DEPS.paramByName("reverse"), "Show reverse dependencies (incoming instead of outgoing)")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY, "Filter to project classes only, hiding JDK/stdlib noise")}")
        appendLine("    Usage: ${u("package-deps")}")
        appendLine("    Usage: ${u("package-deps", p("package", "services"))}")
        appendLine("    Usage: ${u("package-deps", p("package", "\"ktor\\\\.routes\""))}")
        appendLine("    Usage: ${u("package-deps", p("reverse", "true"))}")
        appendLine("    Usage: ${u("package-deps", p("package", "domain"), p("reverse", "true"))}")
        appendLine("    Usage: ${u("package-deps", p("projectonly", "true"))}")
        appendLine()
        appendLine("  ${t("find-usages")}")
        appendLine("    Finds project references to external types or methods.")
        appendLine("    Scans compiled bytecode for method calls, field accesses, and type references")
        appendLine("    matching the specified ownerClass/method or type. Owner-aware — distinguishes")
        appendLine("    same-named methods on different types. Finds Kotlin property accessors by")
        appendLine("    their bytecode name (e.g., getMonthNumber for .monthNumber).")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.FIND_USAGES.paramByName("ownerClass"), "FQN of type — matches method call and field owners")}")
        appendLine("      ${pd(TaskRegistry.METHOD, "Specific method/field name on the owner")}")
        appendLine("      ${pd(TaskRegistry.FIND_USAGES.paramByName("type"), "Find ALL references to a class: calls, fields, casts, signatures")}")
        appendLine("      ${pd(TaskRegistry.FIND_USAGES.paramByName("outside-package"), "Exclude callers inside this package (show only external usages)")}")
        appendLine("      * Provide either 'ownerClass' or 'type'. Use 'type' for comprehensive search.")
        appendLine("    Usage: ${u("find-usages", p("ownerClass", "kotlinx.datetime.LocalDate"), p("method", "getMonthNumber"))}")
        appendLine("    Usage: ${u("find-usages", p("ownerClass", "kotlinx.datetime.Clock"))}")
        appendLine("    Usage: ${u("find-usages", p("type", "kotlinx.datetime.Instant"))}")
        appendLine("    Usage: ${u("find-usages", p("type", "kotlinx.datetime.Instant"), p("outside-package", "com.example.datetime"))}")
        appendLine()
        appendLine("  ${t("dsm")}")
        appendLine("    Shows a Dependency Structure Matrix (DSM) — a compact grid view of inter-package")
        appendLine("    dependencies. Row depends on column; cells show reference counts. Highlights cyclic")
        appendLine("    dependencies with class-level detail.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.DSM.paramByName("root-package"), "Only include packages under this prefix")}")
        appendLine("      ${pd(TaskRegistry.DSM.paramByName("dsm-depth"), "Package depth to group by")}")
        appendLine("      ${pd(TaskRegistry.DSM.paramByName("dsm-html"), "Write interactive HTML matrix to file")}")
        appendLine("      ${pd(TaskRegistry.DSM.paramByName("cycles"), "Show only cyclic dependencies with class-level edges")}")
        appendLine("      ${pd(TaskRegistry.DSM.paramByName("cycle"), "Show only the cycle between two specific packages")}")
        appendLine("    Usage: ${u("dsm")}")
        appendLine("    Usage: ${u("dsm", p("root-package", "com.example"), p("dsm-depth", "3"))}")
        appendLine("    Usage: ${u("dsm", p("dsm-html", "build/dsm.html"))}")
        appendLine("    Usage: ${u("dsm", p("cycles", "true"))}")
        appendLine("    Usage: ${u("dsm", p("cycle", "api,service"))}")
        appendLine()
        appendLine("  ${t("cycles")}")
        appendLine("    Detects dependency cycles using Tarjan's SCC (Strongly Connected Components) algorithm.")
        appendLine("    Unlike '${t("dsm")} ${p("cycles", "true")}' which only finds pairwise bidirectional edges (A<->B),")
        appendLine("    this finds true multi-node cycles (A->B->C->A). Shows class-level edges for each cycle.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.CYCLE_DETECTION.paramByName("root-package"), "Only include packages under this prefix")}")
        appendLine("      ${pd(TaskRegistry.CYCLE_DETECTION.paramByName("dsm-depth"), "Package depth to group by")}")
        appendLine("    Usage: ${u("cycles")}")
        appendLine("    Usage: ${u("cycles", p("root-package", "com.example"), p("dsm-depth", "3"))}")
        appendLine()
        appendLine("  ${t("rank")}")
        appendLine("    Ranks types by structural importance using PageRank on the call graph.")
        appendLine("    Types that are called by many important types score higher. Useful for")
        appendLine("    identifying core abstractions, god classes, and critical dependencies.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.TOP, "Maximum results to return")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY, "Filter to project classes only")}")
        appendLine("    Usage: ${u("rank")}")
        appendLine("    Usage: ${u("rank", p("top", "20"))}")
        appendLine("    Usage: ${u("rank", p("projectonly", "false"))}")
        appendLine()
        appendLine("  ${t("dead")}")
        appendLine("    Finds potential dead code — classes and methods never referenced by other project code.")
        appendLine("    Reports classes with no incoming type-level references and methods with no cross-class callers.")
        appendLine("    Kotlin noise (data class boilerplate, companion objects, coroutine inner classes,")
        appendLine("    bridge methods, static initializers) is automatically filtered out.")
        appendLine("    Results are 'potential' dead code — reflection-based usage cannot be detected from bytecode.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.DEAD.paramByName("filter"), "Only show results matching this regex")}")
        appendLine("      ${pd(TaskRegistry.DEAD.paramByName("exclude"), "Exclude results matching this regex (e.g. entry points, tests)")}")
        appendLine("      ${pd(TaskRegistry.DEAD.paramByName("classes-only"), "Show only unreferenced classes, skip dead methods")}")
        appendLine("    Usage: ${u("dead")}")
        appendLine("    Usage: ${u("dead", p("filter", "\"service\""))}")
        appendLine("    Usage: ${u("dead", p("exclude", "\"Main|Test|Application\""))}")
        appendLine("    Usage: ${u("dead", p("classes-only", "true"))}")
        appendLine()
        appendLine("  ${t("complexity")}")
        appendLine("    Shows fan-in/fan-out complexity for classes matching a regex pattern.")
        appendLine("    Fan-out: how many calls go from this class to other classes (outgoing coupling).")
        appendLine("    Fan-in: how many calls come into this class from other classes (incoming coupling).")
        appendLine("    Without ${TaskRegistry.COMPLEXITY.paramByName("classname").render(tool)}, shows all project classes sorted by fan-out descending.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.COMPLEXITY.paramByName("classname"), "Class name regex to analyze")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY, "Filter to project classes only")}")
        appendLine("      ${pd(TaskRegistry.COMPLEXITY.paramByName("detail"), "Show individual call details")}")
        appendLine("      ${pd(TaskRegistry.TOP, "Maximum results to return")}")
        appendLine("    Usage: ${u("complexity")}")
        appendLine("    Usage: ${u("complexity", p("classname", "Service"))}")
        appendLine("    Usage: ${u("complexity", p("classname", "\".*Controller\""), p("projectonly", "false"))}")
        appendLine("    Usage: ${u("complexity", p("classname", "\"domain\\\\..*\""), p("detail", "true"))}")
        appendLine()
        appendLine("  ${t("metrics")}")
        appendLine("    Quick project health snapshot combining bytecode analysis and git history.")
        appendLine("    Shows: total classes, packages, average fan-in/fan-out, cycle count,")
        appendLine("    dead classes/methods, and top hotspots.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER, "Only consider commits after this date")}")
        appendLine("      ${pd(TaskRegistry.TOP, "Number of hotspots to show")}")
        appendLine("      ${pd(TaskRegistry.METRICS.paramByName("root-package"), "Root package prefix for cycle detection")}")
        appendLine("      ${pd(TaskRegistry.NO_FOLLOW, "Disable git rename tracking")}")
        appendLine("    Usage: ${u("metrics")}")
        appendLine("    Usage: ${u("metrics", p("top", "10"), p("after", "2024-01-01"))}")
        appendLine("    Usage: ${u("metrics", p("root-package", "com.example"))}")
        appendLine()
        appendLine("  ${t("agent-help")}")
        appendLine("    Shows detailed instructions for AI coding agents on how to use code-navigator effectively.")
        appendLine("    Includes recommended workflows, task selection guidance, and tips for optimal results.")
        appendLine("    Usage: ${u("agent-help")}")
        appendLine()
        appendLine("  ${t("config-help")}")
        appendLine("    Lists all available configuration parameters with defaults")
        appendLine("    and which tasks they apply to.")
        appendLine("    Usage: ${u("config-help")}")
        appendLine()
        appendLine("--- Git History Analysis Tasks ---")
        appendLine()
        appendLine("These tasks analyze git history and do NOT require compilation.")
        appendLine("All share the parameter: ${TaskRegistry.AFTER.render(tool)} (default: ${TaskRegistry.AFTER.defaultValue})")
        appendLine("Git rename tracking is enabled by default (-M flag). Use ${TaskRegistry.NO_FOLLOW.render(tool)} to disable it.")
        appendLine()
        appendLine("  ${t("hotspots")}")
        appendLine("    Ranks files by change frequency. The most-changed files are where development")
        appendLine("    effort concentrates — priority refactoring targets if they also have structural problems.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER, "Only consider commits after this date")}")
        appendLine("      ${pd(TaskRegistry.MIN_REVS, "Minimum revisions to include")}")
        appendLine("      ${pd(TaskRegistry.TOP, "Maximum results to return")}")
        appendLine("    Usage: ${u("hotspots")}")
        appendLine("    Usage: ${u("hotspots", p("after", "2024-01-01"), p("min-revs", "5"), p("top", "20"))}")
        appendLine()
        appendLine("  ${t("coupling")}")
        appendLine("    Finds files that change together in the same commits — implicit dependencies invisible")
        appendLine("    in call graphs. Complements structural ${t("package-deps")} with behavioral coupling data.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER, "Only consider commits after this date")}")
        appendLine("      ${pd(TaskRegistry.COUPLING.paramByName("min-shared-revs"), "Minimum shared commits to report")}")
        appendLine("      ${pd(TaskRegistry.COUPLING.paramByName("min-coupling"), "Minimum coupling degree %")}")
        appendLine("      ${pd(TaskRegistry.COUPLING.paramByName("max-changeset-size"), "Skip commits touching more files")}")
        appendLine("      ${pd(TaskRegistry.TOP, "Maximum results to return")}")
        appendLine("    Usage: ${u("coupling")}")
        appendLine("    Usage: ${u("coupling", p("min-shared-revs", "10"), p("min-coupling", "50"))}")
        appendLine()
        appendLine("  ${t("code-age")}")
        appendLine("    Measures time since last modification per file. Stable old code is good;")
        appendLine("    frequently-changing old code with structural problems is a hotspot.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER, "Only consider commits after this date")}")
        appendLine("      ${pd(TaskRegistry.TOP, "Maximum results to return")}")
        appendLine("    Usage: ${u("code-age")}")
        appendLine("    Usage: ${u("code-age", p("after", "2023-01-01"), p("top", "20"))}")
        appendLine()
        appendLine("  ${t("authors")}")
        appendLine("    Number of distinct contributors per file. More developers on a module means")
        appendLine("    larger communication challenges. High author counts correlate with defects.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER, "Only consider commits after this date")}")
        appendLine("      ${pd(TaskRegistry.MIN_REVS, "Minimum revisions to include")}")
        appendLine("      ${pd(TaskRegistry.TOP, "Maximum results to return")}")
        appendLine("    Usage: ${u("authors")}")
        appendLine("    Usage: ${u("authors", p("min-revs", "3"), p("top", "20"))}")
        appendLine()
        appendLine("  ${t("churn")}")
        appendLine("    Measures lines added/deleted per file. Pre-release churn is a good predictor")
        appendLine("    of post-release defects.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER, "Only consider commits after this date")}")
        appendLine("      ${pd(TaskRegistry.TOP, "Maximum results to return")}")
        appendLine("    Usage: ${u("churn")}")
        appendLine("    Usage: ${u("churn", p("after", "2024-06-01"), p("top", "30"))}")
    }

    private fun paramDoc(param: ParamDef, tool: BuildTool, description: String): String {
        val rendered = param.render(tool)
        val annotation = when {
            param.defaultValue != null -> "(optional, default: ${param.defaultValue})"
            param.flag -> "(optional)"
            else -> "(required)"
        }
        return "$rendered  $annotation $description"
    }
}

