package no.f12.codenavigator.navigation

object DsmHtmlRenderer {

    fun render(matrix: DsmMatrix): String {
        val packages = matrix.packages
        return buildString {
            appendLine("<!DOCTYPE html>")
            appendLine("<html lang=\"en\">")
            appendLine("<head>")
            appendLine("<meta charset=\"UTF-8\">")
            appendLine("<title>DSM — Dependency Structure Matrix</title>")
            appendLine("<style>")
            appendLine(CSS)
            appendLine("</style>")
            appendLine("</head>")
            appendLine("<body>")
            appendLine("<h1>Dependency Structure Matrix</h1>")

            if (packages.isEmpty()) {
                appendLine("<p>No inter-package dependencies found.</p>")
                appendLine("</body></html>")
                return@buildString
            }

            appendLine(
                "<p class=\"note\">Row depends on column. " +
                    "<span style=\"color:#155724\">Green = forward dependency (expected)</span>, " +
                    "<span style=\"color:#721c24\">Red = backward dependency (potential cycle, review)</span>.</p>",
            )

            appendLine("<details><summary>Package legend</summary><ol>")
            packages.forEach { pkg -> appendLine("<li>${pkg.value}</li>") }
            appendLine("</ol></details>")

            appendLine("<table>")
            appendLine("<tr><th></th>")
            packages.forEachIndexed { i, _ -> appendLine("<th>${i + 1}</th>") }
            appendLine("</tr>")

            packages.forEachIndexed { rowIdx, rowPkg ->
                appendLine("<tr>")
                appendLine("<td class=\"row-label\">${rowIdx + 1}. ${rowPkg.value}</td>")
                packages.forEachIndexed { colIdx, colPkg ->
                    val count = matrix.cells[rowPkg to colPkg]
                    when {
                        rowIdx == colIdx -> appendLine("<td class=\"diagonal\">\u00b7</td>")
                        count == null -> appendLine("<td class=\"empty\"></td>")
                        else -> {
                            val cssClass = if (rowIdx > colIdx) "forward" else "backward"
                            val deps = matrix.classDependencies[rowPkg to colPkg]
                                ?.joinToString("<br>") { (src, tgt) -> "${src.value} -> ${tgt.value}" }
                                ?: ""
                            appendLine("<td class=\"$cssClass\" style=\"position:relative\">$count")
                            if (deps.isNotEmpty()) {
                                appendLine("<div class=\"tooltip\"><strong>${rowPkg.value} -> ${colPkg.value}</strong><br>$deps</div>")
                            }
                            appendLine("</td>")
                        }
                    }
                }
                appendLine("</tr>")
            }

            appendLine("</table>")
            appendLine("<p class=\"note\">Generated by code-navigator. Analyzed ${packages.size} packages.</p>")
            appendLine("</body></html>")
        }
    }

    private val CSS = """
        body { font-family: 'Segoe UI', system-ui, sans-serif; margin: 2rem; background: #f8f9fa; }
        h1 { color: #212529; }
        table { border-collapse: collapse; font-size: 0.85rem; }
        th, td { border: 1px solid #dee2e6; padding: 4px 8px; text-align: center; min-width: 36px; }
        th { background: #e9ecef; font-weight: 600; }
        td.diagonal { background: #343a40; color: #343a40; }
        td.empty { background: #fff; }
        td.forward { background: #d4edda; color: #155724; font-weight: 600; cursor: pointer; }
        td.backward { background: #f8d7da; color: #721c24; font-weight: 600; cursor: pointer; }
        td.row-label { text-align: left; background: #e9ecef; font-weight: 600; white-space: nowrap; }
        .tooltip { display: none; position: absolute; background: #fff; border: 1px solid #adb5bd;
                   padding: 8px 12px; border-radius: 4px; box-shadow: 0 2px 8px rgba(0,0,0,0.15);
                   font-size: 0.8rem; z-index: 10; max-width: 400px; text-align: left; }
        td:hover .tooltip { display: block; }
        .note { margin-top: 1rem; font-size: 0.85rem; color: #6c757d; }
    """.trimIndent()
}
